# Generated by Django 3.2.7 on 2022-02-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_name',
        ),
    ]
